"""Small repository boundaries for the main Studio runtime domains."""

from typing import Protocol

from backend.models.destination import ResultDelivery, ResultDestination
from backend.models.run import Run
from backend.models.provider import ProviderConnection
from backend.models.tool import ToolConnection
from backend.models.tree import Tree


class TreeRepository(Protocol):
    def get(self, tree_id: str) -> Tree | None: ...
    def list(self) -> list[Tree]: ...
    def add(self, tree: Tree) -> None: ...


class RunRepository(Protocol):
    def get(self, run_id: str) -> Run | None: ...
    def list(self, *, status: str | None = None, tree_id: str | None = None) -> list[Run]: ...
    def add(self, run: Run) -> None: ...


class DestinationRepository(Protocol):
    def get(self, destination_id: str) -> ResultDestination | None: ...
    def list_for_tree(self, tree_id: str, *, enabled_only: bool = False) -> list[ResultDestination]: ...
    def add(self, destination: ResultDestination) -> None: ...
    def add_delivery(self, delivery: ResultDelivery) -> None: ...


class DashboardRepository(Protocol):
    def list_trees(self) -> list[Tree]: ...
    def list_runs(self) -> list[Run]: ...
    def list_providers(self) -> list[ProviderConnection]: ...
    def list_tools(self) -> list[ToolConnection]: ...
