import { render, screen, fireEvent, waitFor, act, within } from '@testing-library/react'
import { vi, it, beforeEach, expect } from 'vitest'
import { createMemoryRouter, RouterProvider } from 'react-router-dom'
import { api } from '@/lib/api'
import { TreePlaygroundPage } from './tree-playground'
import i18n from '@/i18n'
import { emptyExecutionJournal } from '@/lib/playground-execution'
import { emptyLiveModel } from '@/lib/run-live'
const { state, permissions } = vi.hoisted(() => ({ state: { run: null as unknown, detail: null as unknown, artifacts: [] as unknown[] }, permissions: { run: true } }))
vi.mock('@/auth',()=>({useAuth:()=>({can:(permission:string)=>permission==='use_trees'?permissions.run:true})}))
vi.mock('@/components/tree/builder/canvas',()=>({BuilderCanvas:(p:{readOnly:boolean})=><div>Shared canvas {p.readOnly?'observation':'edit'}</div>}))
vi.mock('@/lib/use-playground-run',()=>({usePlaygroundRun:()=>({...state,model:emptyLiveModel,journal:emptyExecutionJournal,connection:'ended',error:null,lostAccess:false,refresh:vi.fn()})}))
const tree={id:'tree',name:'Explicit Tree',status:'ready',current_version_id:'v1',version:{id:'v1',status:'ready',agents:[],tool_assignments:[]}}
async function mount(path='/trees/tree/playground') { const router=createMemoryRouter([{path:'/trees/:treeId/playground',element:<TreePlaygroundPage/>},{path:'/trees/:treeId/build',element:<p>Builder destination</p>},{path:'/trees/:treeId',element:<p>Connect destination</p>},{path:'/executions/:runId',element:<p>Trace destination</p>}],{initialEntries:[path]});render(<RouterProvider router={router}/>);await screen.findByText('Explicit Tree');return router }
beforeEach(async()=>{vi.restoreAllMocks();await i18n.changeLanguage('en');state.run=null;state.detail=null;state.artifacts=[];permissions.run=true;vi.spyOn(api,'getTree').mockResolvedValue(tree as never);vi.spyOn(api,'validateTree').mockResolvedValue({valid:true,errors:[],validated_at:''});vi.spyOn(api,'listTreeRuns').mockResolvedValue([]);vi.spyOn(api,'listProviders').mockResolvedValue([]);vi.spyOn(api,'listTools').mockResolvedValue([])})
it('Ready Tree exposes real submission with explicit Tree ID',async()=>{vi.spyOn(api,'submitLiveRun').mockResolvedValue({run_id:'real-new-id'});const router=await mount();fireEvent.change(screen.getByLabelText('Test input'),{target:{value:'Independent objective'}});fireEvent.click(screen.getByRole('button',{name:'Run Tree'}));await waitFor(()=>expect(api.submitLiveRun).toHaveBeenCalledWith('tree','Independent objective','fast'));expect(router.state.location.search).toBe('?run=real-new-id')})
it('backend blockers gate execution and link Builder',async()=>{vi.mocked(api.validateTree).mockResolvedValue({valid:false,errors:[{code:'missing_model',message:'Missing Model',agent_id:null,step:'agents'}],validated_at:''});const router=await mount();expect(screen.getByRole('button',{name:'Run Tree'})).toBeDisabled();expect(screen.getByText('Missing Model')).toBeVisible();fireEvent.click(screen.getAllByRole('button',{name:'Open Builder'})[0]);expect(router.state.location.pathname).toBe('/trees/tree/build')})
it('observation canvas is the shared renderer',async()=>{await mount();expect(screen.getByText('Shared canvas observation')).toBeVisible()})
it('Run Again prepares input and next submission creates a new ID',async()=>{state.run={run_id:'old',tree_id:'tree',tree_version_id:'v1',status:'completed',final_output:'Result'};state.detail={id:'old',input:{input:'Reuse me'}};vi.spyOn(api,'submitLiveRun').mockResolvedValue({run_id:'new'});const router=await mount('/trees/tree/playground?run=old');await screen.findByDisplayValue('Reuse me');fireEvent.click(screen.getByRole('button',{name:'Run Again'}));expect(router.state.location.search).toBe('');state.run=null;state.detail=null;fireEvent.click(screen.getByRole('button',{name:'Run Tree'}));await waitFor(()=>expect(router.state.location.search).toBe('?run=new'))})
it('Trace and Connect preserve actual IDs',async()=>{state.run={run_id:'run-id',tree_id:'tree',tree_version_id:'v1',status:'completed',final_output:{items:[1]},final_status:'completed'};const router=await mount('/trees/tree/playground?run=run-id');expect(screen.getByLabelText('Result')).toHaveTextContent('items');fireEvent.click(screen.getByRole('button',{name:'Open Execution Trace'}));expect(router.state.location.pathname).toBe('/executions/run-id')})
it('Connect bridge uses the explicit Tree',async()=>{state.run={tree_id:'tree',tree_version_id:'v1',status:'completed',final_output:'Done'};const router=await mount('/trees/tree/playground?run=id');fireEvent.click(screen.getByRole('button',{name:'Connect this Tree'}));expect(router.state.location.pathname+router.state.location.search).toBe('/trees/tree?tab=connect')})
it('cancellation request waits for backend confirmation',async()=>{state.run={tree_id:'tree',tree_version_id:'v1',status:'cancellation_requested'};await mount('/trees/tree/playground?run=id');expect(screen.getByRole('button',{name:'Cancel Run'})).toBeDisabled();expect(screen.getAllByText('Cancellation requested')[0]).toBeVisible()})
it('JSON invalid input never starts a Run',async()=>{const submit=vi.spyOn(api,'submitLiveRun');await mount();fireEvent.change(screen.getByLabelText('Input format'),{target:{value:'json'}});fireEvent.change(screen.getByLabelText('Test input'),{target:{value:'{bad'}});fireEvent.click(screen.getByRole('button',{name:'Run Tree'}));expect(await screen.findByText('Enter valid JSON before running.')).toBeVisible();expect(submit).not.toHaveBeenCalled()})
it('permission-aware execution is disabled',async()=>{permissions.run=false;await mount();expect(screen.getByRole('button',{name:'Run Tree'})).toBeDisabled();expect(screen.getByText(/need Tree execution permission/)).toBeVisible()})
it('language changes naturally while product terms remain English',async()=>{await mount();await act(()=>i18n.changeLanguage('th'));expect(screen.getByText('ทดสอบ Tree ของคุณ')).toBeVisible();expect(screen.getByRole('button',{name:'เริ่ม Run'})).toBeVisible();expect(screen.queryByText(/เอเจนต์|พรอไวเดอร์|รัน/)).not.toBeInTheDocument();await act(()=>i18n.changeLanguage('en'));expect(screen.getByText('Test your Tree')).toBeVisible()})
it('persisted artifacts use the existing Run artifact transport',async()=>{state.run={tree_id:'tree',tree_version_id:'v1',status:'completed',final_output:'Done'};state.artifacts=[{artifact_id:'artifact-id',name:'analysis.json',type:'file',media_type:'application/json',created_at:'2026-10-01T00:00:00Z',sha256:'1234567890abcdef',is_final:true,body_available:true,size_bytes:12,producer_role:'specialist',operation:'create'}];const fetch=vi.spyOn(api,'fetchLiveArtifact').mockResolvedValue(new Blob(['{"ok":true}']));await mount('/trees/tree/playground?run=run-id');expect(screen.getByText('analysis.json')).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Preview'}));await waitFor(()=>expect(fetch).toHaveBeenCalledWith('run-id','artifact-id'));expect(await screen.findByText('{"ok":true}')).toBeVisible()})
it('valid configuration still requires persisted Ready status',async()=>{vi.mocked(api.getTree).mockResolvedValue({...tree,status:'draft',version:{...tree.version,status:'draft'}} as never);await mount();fireEvent.change(screen.getByLabelText('Test input'),{target:{value:'test'}});expect(screen.getByRole('button',{name:'Run Tree'})).toBeDisabled();expect(screen.getAllByText('Valid configuration · Draft')[0]).toBeVisible();expect(screen.getByText(i18n.t("playground.markReadyHelp"))).toBeVisible()})

it('partial outcome has one primary Partial status and no green completion guidance',async()=>{state.run={tree_id:'tree',tree_version_id:'v1',status:'completed',final_output:'Partial answer',final_status:'partial'};await mount('/trees/tree/playground?run=id');expect(screen.getByText('Partial')).toBeVisible();expect(within(screen.getByText('Partial').closest('footer')!).queryByText('Completed')).not.toBeInTheDocument();expect(screen.queryByText('Test finished. Inspect the trace or connect this Tree.')).not.toBeInTheDocument();expect(screen.getByText(i18n.t("integrationPolish.partialResult"))).toBeVisible()})

it('Input, shared Canvas and Activity are three sibling panes with existing content',async()=>{
 await mount()
 const test=screen.getByRole('region',{name:'Test your Tree'})
 const graph=screen.getByRole('region',{name:'Live Execution'})
 const activity=screen.getByRole('region',{name:i18n.t('playground.timeline')})
 expect(test.parentElement).toBe(graph.parentElement)
 expect(graph.parentElement).toBe(activity.parentElement)
 expect([...graph.parentElement!.children]).toEqual([test,graph,activity])
 expect(graph).toHaveTextContent('Shared canvas observation')
 expect(activity).toHaveTextContent(i18n.t('playground.timelineEmpty'))
 expect(within(test).getByRole('button',{name:'Run Tree'})).toBeVisible()
})

it('Deep selection reaches the existing Run service with explicit mode',async()=>{const submit=vi.spyOn(api,'submitLiveRun').mockResolvedValue({run_id:'deep-id'});await mount();expect(screen.getByRole('button',{name:'Fast'})).toHaveAttribute('aria-pressed','true');fireEvent.click(screen.getByRole('button',{name:'Deep'}));expect(screen.getByRole('button',{name:'Deep'})).toHaveAttribute('aria-pressed','true');fireEvent.change(screen.getByLabelText('Test input'),{target:{value:'Compare'}});fireEvent.click(screen.getByRole('button',{name:'Run Tree'}));await waitFor(()=>expect(submit).toHaveBeenCalledWith('tree','Compare','deep'))})
it('persisted Deep mode restores and cannot change during active execution',async()=>{state.run={run_id:'id',tree_id:'tree',tree_version_id:'v1',status:'running',execution_mode:'deep'};await mount('/trees/tree/playground?run=id');expect(screen.getByRole('button',{name:'Deep'})).toHaveAttribute('aria-pressed','true');expect(screen.getByRole('button',{name:'Fast'})).toBeDisabled()})
it('Thai mode keeps Fast/Deep and Agent hierarchy terms recognizable',async()=>{await act(()=>i18n.changeLanguage('th'));await mount();expect(screen.getByRole('button',{name:'Fast'})).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Deep'}));expect(screen.getByText(i18n.t('playground.modeHelp.deep'))).toHaveTextContent('Manager และ Specialist');await act(()=>i18n.changeLanguage('en'))})
