import { FlaskConical, Pencil, RadioTower, RefreshCw, Search, Trash2 } from "lucide-react"

import { ToolStatusBadge } from "@/components/tools/tool-status-badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import type { ToolConnection } from "@/lib/api"

export function ToolCard({ tool, busy, onTest, onDiscover, onExecute, onEdit, onDelete }: { tool: ToolConnection; busy: boolean; onTest: () => void; onDiscover: () => void; onExecute: () => void; onEdit: () => void; onDelete: () => void }) {
  return <Card><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2">{tool.tool_type === "mcp" ? <RadioTower className="size-5" /> : <FlaskConical className="size-5" />}{tool.name}</CardTitle><CardDescription className="mt-1">{tool.description || (tool.tool_type === "mcp" ? "MCP connection" : "HTTP API Tool")}</CardDescription></div><ToolStatusBadge status={tool.status} /></div></CardHeader><CardContent><div className="grid grid-cols-3 gap-3 rounded-lg bg-muted/35 p-3 text-sm"><div><p className="text-xs text-muted-foreground">Type</p><p className="mt-1">{tool.tool_type === "mcp" ? "MCP" : "HTTP API"}</p></div><div><p className="text-xs text-muted-foreground">Assigned</p><p className="mt-1">{tool.assigned_agents_count} Agents</p></div><div><p className="text-xs text-muted-foreground">Last checked</p><p className="mt-1 text-xs">{tool.last_checked_at ? new Date(tool.last_checked_at).toLocaleString() : "Never"}</p></div></div>{tool.last_error ? <p className="mt-3 text-xs text-red-600 dark:text-red-300">{tool.last_error}</p> : null}<div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" disabled={busy || !tool.enabled} onClick={onTest}><RefreshCw className="size-4" />Test Connection</Button>{tool.tool_type === "mcp" ? <Button variant="outline" disabled={busy || !tool.enabled} onClick={onDiscover}><Search className="size-4" />Discover</Button> : null}<Button variant="outline" disabled={busy || tool.status !== "connected"} onClick={onExecute}><FlaskConical className="size-4" />Test Execute</Button><Button variant="ghost" disabled={busy} onClick={onEdit}><Pencil className="size-4" />Edit</Button><Button variant="ghost" disabled={busy} className="text-red-600" onClick={onDelete}><Trash2 className="size-4" />Delete</Button></div></CardContent></Card>
}
