import { beforeEach, describe, expect, it } from 'vitest'
import { addAgent, attachTool, autoLayout, canConnect, connectAgents, deleteAgents, detachTool, layoutKey, newDocument, readLayout, resourceId, treeDocument, writeLayout } from './model'
import type { TreeDetail } from '@/lib/api'
function hierarchy() {
  let doc = addAgent(newDocument(), 'root'); const root = doc.agents[0].id
  doc = addAgent(doc, 'manager', root); const manager = doc.agents[1].id
  doc = addAgent(doc, 'specialist', manager); return doc
}
describe('Builder document contracts', () => {
  beforeEach(() => localStorage.clear())
  it('starts empty without synthesizing a Root', () => { expect(newDocument().agents).toEqual([]) })
  it('prevents a second Root before save', () => { expect(() => addAgent(addAgent(newDocument(), 'root'), 'root')).toThrow('rootExists') })
  it('creates real IDs and explicit parents', () => { const doc = hierarchy(); expect(new Set(doc.agents.map(a => a.id)).size).toBe(3); expect(doc.agents[2].parent_agent_id).toBe(doc.agents[1].id) })
  it('leaves canvas additions unconnected rather than guessing', () => { const doc = addAgent(hierarchy(), 'manager'); expect(doc.agents.at(-1)?.parent_agent_id).toBeNull() })
  it('accepts Root → Manager and Manager → Specialist', () => { const doc = hierarchy(); expect(canConnect(doc, doc.agents[0].id, doc.agents[1].id)).toBe(true); expect(canConnect(doc, doc.agents[1].id, doc.agents[2].id)).toBe(true) })
  it('rejects every other hierarchy pairing without mutating', () => { const doc = hierarchy(), original = structuredClone(doc); expect(() => connectAgents(doc, doc.agents[2].id, doc.agents[1].id)).toThrow(); expect(() => connectAgents(doc, doc.agents[0].id, doc.agents[2].id)).toThrow(); expect(doc).toEqual(original) })
  it('reparents explicitly and keeps exactly one parent', () => { let doc = hierarchy(); doc = addAgent(doc, 'manager', doc.agents[0].id); doc = connectAgents(doc, doc.agents[3].id, doc.agents[2].id); expect(doc.agents[2].parent_agent_id).toBe(doc.agents[3].id) })
  it('uses the same binding for Tool and MCP and prevents duplicate attachments', () => { let doc = hierarchy(); doc = attachTool(doc, doc.agents[0].id, 'mcp'); expect(attachTool(doc, doc.agents[0].id, 'mcp')).toBe(doc); expect(() => attachTool(doc, 'missing', 'tool')).toThrow(); expect(doc.tool_assignments[0]).toEqual({ agent_config_id: doc.agents[0].id, tool_connection_id: 'mcp' }) })
  it('keeps a shared Tool resource while removing only the selected Agent binding', () => { let doc = hierarchy(); doc = attachTool(doc, doc.agents[1].id, 'tool'); doc = attachTool(doc, doc.agents[2].id, 'tool'); const next = detachTool(doc, doc.agents[1].id, 'tool'); expect(next.tool_assignments).toEqual([{ agent_config_id: doc.agents[2].id, tool_connection_id: 'tool' }]); expect(resourceId('tool')).toBe('resource:tool') })
  it('deletes descendants and bindings without orphaning Agents', () => { let doc = hierarchy(); doc = attachTool(doc, doc.agents[2].id, 'tool'); const next = deleteAgents(doc, [doc.agents[1].id]); expect(next.agents).toHaveLength(1); expect(next.tool_assignments).toEqual([]) })
  it('clears removed Manager collaboration references', () => { let doc = hierarchy(); doc = addAgent(doc, 'manager', doc.agents[0].id); doc.agents[3].settings = { allowed_manager_peer_ids: [doc.agents[1].id], custom: true }; const next = deleteAgents(doc, [doc.agents[1].id]); expect(next.agents[1].settings).toEqual({ allowed_manager_peer_ids: [], custom: true }) })
  it('derives old/Template records without dropping unconnected Agents or legacy fields', () => { const doc = hierarchy(); doc.agents[2].parent_agent_id = null; doc.template = 'incident'; doc.trigger = { trigger_type: 'webhook', config: { route: 'legacy' } }; const tree = { name: doc.name, description: doc.description, template: doc.template, version: doc } as unknown as TreeDetail; expect(treeDocument(tree)).toEqual(doc); expect(treeDocument(tree)).not.toBe(doc) })
  it('lays out 25 Agents and one shared resource in a dedicated lane', () => { let doc = addAgent(newDocument(), 'root'); for (let m = 0; m < 4; m++) { doc = addAgent(doc, 'manager', doc.agents[0].id); const manager = doc.agents.at(-1)!.id; for (let s = 0; s < 5; s++) { doc = addAgent(doc, 'specialist', manager); doc = attachTool(doc, doc.agents.at(-1)!.id, 'tool') } } const layout = autoLayout(doc); expect(Object.keys(layout)).toHaveLength(26); expect(Object.keys(layout).filter(id => id.startsWith('resource:'))).toEqual(['resource:tool']); const agentsRight = Math.max(...doc.agents.map(agent => layout[agent.id].x + 250)); expect(layout['resource:tool'].x).toBeGreaterThan(agentsRight); expect(new Set(Object.values(layout).map(p => `${p.x}:${p.y}`)).size).toBe(26); expect(autoLayout(doc)).toEqual(layout) })
  it('places unassigned Canvas-only resources in the resource lane without changing Tree data', () => { const doc = hierarchy(), layout = autoLayout(doc, ['resource:local']); const agentsRight = Math.max(...doc.agents.map(agent => layout[agent.id].x + 250)); expect(layout['resource:local'].x).toBeGreaterThan(agentsRight); expect(doc.tool_assignments).toEqual([]) })
  it('stores layout, collapse and visual-only resource hiding per user/Tree/version', () => { const key = layoutKey('user', 'tree', 'v1'); writeLayout(key, { a: { x: 10, y: 20 } }, ['a'], ['resource:tool']); expect(readLayout(key)).toEqual({ positions: { a: { x: 10, y: 20 } }, collapsed: ['a'], hiddenResources: ['resource:tool'] }); expect(readLayout(layoutKey('user', 'tree', 'v2')).positions).toEqual({}) })
  it('handles corrupt and invalid layout safely', () => { localStorage.setItem('test', '{'); expect(readLayout('test').positions).toEqual({}); localStorage.setItem('test', JSON.stringify({ positions: { a: { x: 'secret', y: 4 }, b: { x: 1e10, y: 0 } }, collapsed: 'bad', hiddenResources: ['bad'] })); expect(readLayout('test')).toEqual({ positions: {}, collapsed: [], hiddenResources: [] }) })
  it('uses one stable visual ID per shared resource, never Provider nodes', () => { expect(resourceId('agent', 'tool')).toBe('resource:tool'); expect(resourceId('tool')).toBe('resource:tool') })
})
