import { renderHook, waitFor, act } from '@testing-library/react'
import { beforeEach, expect, it, vi } from 'vitest'
import { api, ApiError } from './api'
import { usePlaygroundRun } from './use-playground-run'
import type { openRunStream } from './run-live'
const { transport } = vi.hoisted(()=>({transport:{options:null as Parameters<typeof openRunStream>[1]|null,close:vi.fn()}}))
vi.mock('./run-live',async(importOriginal)=>({...await importOriginal<typeof import('./run-live')>(),openRunStream:vi.fn((_id,options)=>{transport.options=options;return transport.close})}))
const run={run_id:'id',tree_id:'tree',tree_version_id:'v',status:'running',final_output:null}
beforeEach(()=>{vi.restoreAllMocks();transport.options=null;transport.close.mockClear();vi.spyOn(api,'getLiveRun').mockResolvedValue(run as never);vi.spyOn(api,'getRun').mockResolvedValue({id:'id',tree_id:'tree',input:{input:'persisted'}} as never);vi.spyOn(api,'getLiveEvents').mockResolvedValue({events:[],next_after:0,has_more:false});vi.spyOn(api,'getLiveResult').mockResolvedValue({final_output:'Final',final_status:'completed'});vi.spyOn(api,'getLiveArtifacts').mockResolvedValue({artifacts:[]})})
it('attaches the actual Run ID and batches/deduplicates replay events',async()=>{const {result}=renderHook(()=>usePlaygroundRun('id','tree'));await waitFor(()=>expect(transport.options).not.toBeNull());const event={sequence:1,type:'operation.in_flight',agent_id:'spec',agent_name:'Spec',payload:{metadata:{operation_type:'specialist.generate'}},created_at:''};act(()=>{transport.options!.onEvent(event);transport.options!.onEvent(event)});await waitFor(()=>expect(result.current.model.events).toHaveLength(1));expect(transport.options!.cursor()).toBe(1);expect(api.getLiveRun).toHaveBeenCalledWith('id')})
it('temporary disconnection does not fail the Run',async()=>{const {result}=renderHook(()=>usePlaygroundRun('id','tree'));await waitFor(()=>expect(transport.options).not.toBeNull());act(()=>transport.options!.onConnection('reconnecting'));expect(result.current.run?.status).toBe('running');expect(result.current.connection).toBe('reconnecting')})
it('terminal reconciliation obtains persisted result and artifacts without streaming history',async()=>{vi.mocked(api.getLiveRun).mockResolvedValue({...run,status:'completed'} as never);const {result}=renderHook(()=>usePlaygroundRun('id','tree'));await waitFor(()=>expect(result.current.run?.final_output).toBe('Final'));expect(api.getLiveResult).toHaveBeenCalledWith('id');expect(api.getLiveArtifacts).toHaveBeenCalledWith('id');expect(transport.options).toBeNull();expect(result.current.connection).toBe('ended')})
it('refuses a Run belonging to another Tree',async()=>{vi.mocked(api.getLiveRun).mockResolvedValue({...run,tree_id:'other'} as never);const {result}=renderHook(()=>usePlaygroundRun('id','tree'));await waitFor(()=>expect(result.current.lostAccess).toBe(true));expect(result.current.run).toBeNull();expect(transport.options).toBeNull()})
it('access loss clears observed data rather than retaining it',async()=>{const {result}=renderHook(()=>usePlaygroundRun('id','tree'));await waitFor(()=>expect(transport.options).not.toBeNull());act(()=>transport.options!.onAuthorizationLost());expect(result.current.run).toBeNull();expect(result.current.lostAccess).toBe(true);expect(result.current.model.events).toHaveLength(0)})
it('401 fails closed before any event subscription',async()=>{vi.mocked(api.getLiveRun).mockRejectedValue(new ApiError('Unavailable',401));const {result}=renderHook(()=>usePlaygroundRun('id','tree'));await waitFor(()=>expect(result.current.lostAccess).toBe(true));expect(transport.options).toBeNull()})
it('unmount closes the stream',async()=>{const {unmount}=renderHook(()=>usePlaygroundRun('id','tree'));await waitFor(()=>expect(transport.options).not.toBeNull());unmount();expect(transport.close).toHaveBeenCalled()})
it('late terminal fetch cannot repopulate data after authorization loss',async()=>{let finish!:(value:unknown)=>void;vi.mocked(api.getLiveResult).mockImplementation(()=>new Promise(resolve=>{finish=resolve}) as never);const {result}=renderHook(()=>usePlaygroundRun('id','tree'));await waitFor(()=>expect(transport.options).not.toBeNull());vi.mocked(api.getLiveRun).mockResolvedValue({...run,status:'completed'} as never);let refreshing!:Promise<void>;act(()=>{refreshing=result.current.refresh()});await waitFor(()=>expect(api.getLiveResult).toHaveBeenCalled());act(()=>transport.options!.onAuthorizationLost());await act(async()=>{finish({final_output:'Late private output',final_status:'completed'});await refreshing});expect(result.current.lostAccess).toBe(true);expect(result.current.run).toBeNull();expect(result.current.detail).toBeNull();expect(result.current.artifacts).toEqual([])})
